# Generated by Django 6.0.7 on 2026-09-13 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimientoinventario_cantidad'),
        ('variantes', '0002_variante_stock_defectuoso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['-fecha'], name='mov_inv_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['variante', '-fecha'], name='mov_inv_var_fecha_idx'),
        ),
    ]
