# Generated by Django 6.0.7 on 2026-09-13 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte_caja', '0003_alter_movimientocaja_tipo'),
        ('metodos_pago', '0002_alter_metodopago_nombre'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_folio_f7143d_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_usuario_18c0be_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_corte_c_ed1bee_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_estado_b0d674_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='venta_fecha_idx',
            old_name='ventas_vent_fecha_8683f5_idx',
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['corte_caja', 'estado'], name='venta_corte_estado_idx'),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_creacion',
        ),
    ]
