# Generated by Django 6.0.7 on 2026-09-16 05:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_nombre_and_more'),
        ('variantes', '0002_variante_stock_defectuoso'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['producto', 'activo'], name='variante_producto_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='variante_producto_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='variante_sku_lower_unico'),
        ),
    ]
