# Generated by Django 6.0.7 on 2026-10-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantes', '0003_variante_variante_producto_activo_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variante',
            name='variante_producto_nombre_unico',
        ),
        migrations.AlterField(
            model_name='variante',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
