# Generated by Django 6.0.7 on 2026-09-14 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
        ('corte_caja', '0003_alter_movimientocaja_tipo'),
        ('devoluciones', '0003_add_tipo_defectuoso'),
        ('metodos_pago', '0002_alter_metodopago_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cortecaja',
            index=models.Index(fields=['caja', 'fecha_fin'], name='corte_caja__caja_id_a868d0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['corte_caja', 'tipo'], name='corte_caja__corte_c_42e18e_idx'),
        ),
    ]
