# Generated by Django 6.0.7 on 2026-09-15 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
        ('corte_caja', '0004_cortecaja_corte_caja__caja_id_a868d0_idx_and_more'),
        ('devoluciones', '0003_add_tipo_defectuoso'),
        ('metodos_pago', '0002_alter_metodopago_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cortecaja',
            name='corte_caja__caja_id_75a676_idx',
        ),
        migrations.RemoveIndex(
            model_name='cortecaja',
            name='corte_caja__usuario_e0bf2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='cortecaja',
            name='corte_caja__fecha_f_9629f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientocaja',
            name='corte_caja__corte_c_b6a5eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientocaja',
            name='corte_caja__metodo__59e03e_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientocaja',
            name='corte_caja__tipo_a38c98_idx',
        ),
        migrations.RenameIndex(
            model_name='cortecaja',
            new_name='corte_fecha_inicio_idx',
            old_name='corte_caja__fecha_i_9310cb_idx',
        ),
        migrations.RenameIndex(
            model_name='cortecaja',
            new_name='corte_caja_fecha_fin_idx',
            old_name='corte_caja__caja_id_a868d0_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocaja',
            new_name='mov_caja_fecha_idx',
            old_name='corte_caja__fecha_b8080c_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocaja',
            new_name='mov_caja_corte_tipo_idx',
            old_name='corte_caja__corte_c_42e18e_idx',
        ),
        migrations.AddConstraint(
            model_name='cortecaja',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('caja',), name='corte_caja_unico_abierto'),
        ),
        migrations.AddConstraint(
            model_name='cortecaja',
            constraint=models.CheckConstraint(condition=models.Q(('efectivo_inicial__gte', 0)), name='corte_efectivo_inicial_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cortecaja',
            constraint=models.CheckConstraint(condition=models.Q(('efectivo_final__gte', 0), ('efectivo_final__isnull', True), _connector='OR'), name='corte_efectivo_final_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='mov_caja_monto_no_negativo'),
        ),
    ]
