# Generated by Django 6.0.7 on 2026-09-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_venta', '0002_remove_detalleventa_detalle_ven_venta_i_c3ab5b_idx_and_more'),
        ('variantes', '0002_variante_stock_defectuoso'),
        ('ventas', '0002_remove_venta_ventas_vent_folio_f7143d_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.UniqueConstraint(fields=('venta', 'variante'), name='detalle_venta_venta_variante_unica'),
        ),
    ]
