# Generated by Django 6.0.7 on 2026-09-16 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_venta', '0003_detalleventa_detalle_venta_venta_variante_unica'),
        ('garantias', '0001_initial'),
        ('variantes', '0002_variante_stock_defectuoso'),
        ('ventas', '0002_remove_venta_ventas_vent_folio_f7143d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='garantia',
            name='garantias_g_venta_i_68ca4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='garantia',
            name='garantias_g_detalle_e34f48_idx',
        ),
        migrations.RemoveIndex(
            model_name='garantia',
            name='garantias_g_variant_dce793_idx',
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['detalle_venta', 'estado'], name='garantia_detalle_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='garantia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='garantia_cantidad_mayor_cero'),
        ),
    ]
