"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY no está configurada. "
        "Define la variable de entorno SECRET_KEY antes de iniciar el servidor."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "episodes-taught-stayed-processing.trycloudflare.com",
]


CSRF_TRUSTED_ORIGINS = [
    "https://episodes-taught-stayed-processing.trycloudflare.com",
]

# En producción cambiar a False y listar solo los orígenes permitidos.
# Ejemplo: CORS_ALLOWED_ORIGINS = ["https://tu-frontend.com"]
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    
    'corsheaders',
    
    'usuarios',
    'categorias',
    'productos',
    'variantes',
    'inventario',
    'empresa',
    'metodos_pago',
    'cajas',
    'corte_caja',
    'ventas',
    'detalle_venta',
    'tickets',
    'devoluciones',
    'garantias',
    'bitacora',
    'reportes',
    
]

REST_FRAMEWORK = {
    
    
    "EXCEPTION_HANDLER": "config.exceptions.custom_exception_handler",

    # --------------------------------------------------------
    # Autenticación
    # --------------------------------------------------------
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    # --------------------------------------------------------
    # Permiso por defecto: cualquier vista sin permiso
    # explícito queda bloqueada para no-autenticados.
    # --------------------------------------------------------
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    # --------------------------------------------------------
    # Rate limiting global
    # anon  : peticiones sin token (solo login/refresh)
    # user  : peticiones autenticadas
    # login : throttle específico del endpoint de login
    # --------------------------------------------------------
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        "anon":  "60/min",
        "user":  "300/min",
        "login": "10/min",
    },

    # --------------------------------------------------------
    # Paginación global con formato estándar del proyecto.
    # --------------------------------------------------------
    "DEFAULT_PAGINATION_CLASS": "config.pagination.StandardPagination",
    "PAGE_SIZE": 50,

    # --------------------------------------------------------
    # En producción solo JSON, sin Browsable API.
    # --------------------------------------------------------
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ] if not DEBUG else [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":    timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME":   timedelta(days=7),
    "ROTATE_REFRESH_TOKENS":    True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Tipo de header esperado: Authorization: Bearer <token>
    "AUTH_HEADER_TYPES":        ("Bearer",),
    # Campo del modelo de usuario usado como identificador en el token
    "USER_ID_FIELD":            "id",
    "USER_ID_CLAIM":            "user_id",
    # Algoritmo de firma
    "ALGORITHM":                "HS256",
}

MIDDLEWARE = [
    
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE":       "django.db.backends.postgresql",
        "NAME":         os.getenv("DB_NAME"),
        "USER":         os.getenv("DB_USER"),
        "PASSWORD":     os.getenv("DB_PASSWORD"),
        "HOST":         os.getenv("DB_HOST"),
        "PORT":         os.getenv("DB_PORT"),
        # Reutilizar conexiones hasta 60 s en lugar de abrir
        # una nueva por cada request.
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'usuarios.Usuario'


# ==============================================================
# SEGURIDAD HTTP
# ==============================================================

# Evita que el navegador adivine el Content-Type.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Activa el filtro XSS del navegador (IE/Edge legacy).
SECURE_BROWSER_XSS_FILTER = True

# Impide que la app se cargue dentro de un <iframe>
# (protección contra clickjacking).
X_FRAME_OPTIONS = "DENY"

# En producción (DEBUG=False) forzar HTTPS.
if not DEBUG:
    SECURE_SSL_REDIRECT                  = True
    SECURE_HSTS_SECONDS                  = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS       = True
    SECURE_HSTS_PRELOAD                  = True
    SESSION_COOKIE_SECURE                = True
    CSRF_COOKIE_SECURE                   = True
    SECURE_PROXY_SSL_HEADER              = (
        "HTTP_X_FORWARDED_PROTO",
        "https"
    )

