# Generated by Django 6.0.7 on 2026-09-16 03:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_categorias_activo_idx_and_more'),
        ('productos', '0002_rename_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='producto_nombre_lower_unico'),
        ),
    ]
