# Generated by Django 6.0.7 on 2026-09-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_remove_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='singleton_key',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
