# Generated by Django 6.0.7 on 2026-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_venta', '0003_detalleventa_detalle_venta_venta_variante_unica'),
        ('devoluciones', '0003_add_tipo_defectuoso'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalledevolucion',
            constraint=models.UniqueConstraint(fields=('devolucion', 'detalle_venta'), name='detalle_devolucion_unico_por_devolucion'),
        ),
        migrations.AddConstraint(
            model_name='detalledevolucion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='detalle_devolucion_cantidad_positiva'),
        ),
    ]
