# Generated by Django 6.0.7 on 2026-09-13 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario', '-fecha'], name='bitacora_usuario_fa0128_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['modulo'], name='bitacora_modulo_298c06_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['accion'], name='bitacora_accion_401835_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['fecha'], name='bitacora_fecha_ad1d2a_idx'),
        ),
    ]
